FROM rclone/rclone:latest

# Create rclone config
RUN mkdir -p /config
echo "[b2-music]
type = s3
provider = Other
env_auth = false
access_key_id = ${S3_ACCESS_KEY_ID}
secret_access_key = ${S3_SECRET_ACCESS_KEY}
endpoint = ${S3_ENDPOINT}
region = ${S3_REGION}
" > /config/rclone.conf

# Sync command
CMD ["sync", "b2-music:navidrome-flo-music", "/music", "--config", "/config/rclone.conf"]
