# Navidrome Configuration File
# Note: Environment variables take precedence over this file

# Server settings
Address = "0.0.0.0"

# Paths (will be overridden by environment variables)
MusicFolder = "/music"
DataFolder = "/data"

# Scanner settings
ScanSchedule = "@every 24h"
AutoImportPlaylists = true

# Performance settings
TranscodingCacheSize = "300MB"
ImageCacheSize = "300MB"

# Session timeout
SessionTimeout = "24h"

# Enable features
EnableSharing = true
EnableDownloads = true

# Log level
LogLevel = "info"
